config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'spend_budgets/monthly/:year/:month', to: 'spend_budgets#index', as: 'spend_budgets/index'
  resources :spend_budgets

  get 'spends/:year/:month', to: 'spends#index', as: 'spends/index'
  resources :spends

  get 'incomes/:year/:month', to: 'incomes#index', as: 'incomes/index'
  resources :incomes

  resources :transfers

  resources :monthly_closings

  get 'summaries/:year/:month', to: 'summaries#index', as: 'summaries/index'
  resources :summaries

  get 'wallet_summaries', to: 'wallet_summaries#index'
  get 'wallet_summaries/:walletId/:year/:month', to: 'wallet_summaries#show', as: 'wallet_summaries/show'

  post '/callback', to: 'linebot#callback'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    flash.now[:success] = "success!"
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<form>
  <h2>my 家計簿</h2>
  <div class="form-group">
    <%= link_to "よさん", spend_budgets_path, class: "btn btn-block" %>
    </div>
    <div class="form-group">
    <%= link_to "使った", new_spend_path, class: "btn btn-block" %>
    <%= link_to "貰った", new_income_path, class: "btn btn-block" %>
    </div>
    <div class="form-group">
    <%= link_to "振替え", new_transfer_path, class: "btn btn-block" %>
    <%= link_to "月次調整", new_monthly_closing_path, class: "btn btn-block" %>
    </div>
    <div class="form-group">
    <%= link_to "きろく", summaries_path, class: "btn btn-block" %>
    <%= link_to "さいふ", wallet_summaries_path, class: "btn btn-block" %>
  </div>
</form>