config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'spend_budgets/monthly/:year/:month', to: 'spend_budgets#index', as: 'spend_budgets/index'
  resources :spend_budgets

  get 'spends/:year/:month', to: 'spends#index', as: 'spends/index'
  resources :spends

  get 'incomes/:year/:month', to: 'incomes#index', as: 'incomes/index'
  resources :incomes

  resources :transfers

  resources :monthly_closings

  get 'summaries/:year/:month', to: 'summaries#index', as: 'summaries/index'
  resources :summaries

  get 'wallet_summaries', to: 'wallet_summaries#index'
  get 'wallet_summaries/:walletId/:year/:month', to: 'wallet_summaries#show', as: 'wallet_summaries/show'

  post '/callback', to: 'linebot#callback'
end

app/controllers/wallet_summaries_controller.rb
class WalletSummariesController < ApplicationController

  def index
    @p_targetDate = Time.zone.now
    @wallet_summaries = get_wallet_summaries()
  end

  def show
    @p_targetDate = Time.zone.local(params[:year], params[:month], 1, 0, 0, 0)

    @p_walletName = '全て'
    @p_walletName = Wallet.find_by(id: params[:walletId]).name if (params[:walletId].present? && !params[:walletId].blank?)

    @p_walletId = params[:walletId] if (params[:walletId].present?)

    @summary = get_wallet_summary(@p_targetDate)
  end

  private
  def get_wallet_summaries
    wallet_summaries = Wallet.joins('LEFT OUTER JOIN view_financials ON id = wallet_id')
      .select('id', 'name', 'SUM(COALESCE(amount, 0)) AS amount')
      .group('id', 'name')
      .order('id')
    return wallet_summaries
  end

  def get_wallet_summary(targetDate)
    summary =  ViewFinancial.joins(:wallet)
      .joins(:user)
      .select(
        'wallets.id AS wallet_id',
        'wallets.name AS wallet_name',
        'users.name AS user_name',
        'reason_name',
        'amount',
        'view_financials.created_at'
      )
      .where(created_at: targetDate.in_time_zone.all_month)
      .order('created_at desc')
    summary = summary.where(wallet_id: params[:walletId]) if params[:walletId].present?
    return summary
  end

end

app/controllers/wallet_summary_controller.rb
class WalletSummaryController < ApplicationController

  def show
    @p_targetDate = Time.zone.now
    @wallet_summary = get_wallets_summary()
  end

  def detail
    @p_targetDate = Time.zone.local(params[:year], params[:month], 1, 0, 0, 0)
    @p_targetDate = params[:targetDate].to_date if (params[:targetDate].present?)

    @p_walletName = '全て'
    @p_walletName = Wallet.find_by(id: params[:walletId]).name if (params[:walletId].present? && !params[:walletId].blank?)

    @p_walletId = params[:walletId] if (params[:walletId].present?)

    @summary = get_wallet_summary(@p_targetDate)
  end

  private
  def get_wallets_summary
    wallets_summary = Wallet.joins('LEFT OUTER JOIN view_financials ON id = wallet_id')
      .select('id', 'name', 'SUM(COALESCE(amount, 0)) AS amount')
      .group('id', 'name')
      .order('id')
    return wallets_summary
  end

  def get_wallet_summary(targetDate)
    summary =  ViewFinancial.joins(:wallet)
      .joins(:user)
      .select(
        'wallets.id AS wallet_id',
        'wallets.name AS wallet_name',
        'users.name AS user_name',
        'reason_name',
        'amount',
        'view_financials.created_at'
      )
      .where(created_at: targetDate.in_time_zone.all_month)
      .order('created_at desc')
    summary = summary.where(wallet_id: params[:walletId]) if params[:walletId].present?
    return summary
  end

end

app/helpers/wallet_summaries_helper.rb
module WalletSummariesHelper
end

app/helpers/wallet_summary_helper.rb
module WalletSummaryHelper
end

app/views/wallet_summaries/_detail_pager.html.erb
<div class="card">
  <table style="width: 100%;">
    <tbody>
      <tr>
        <td class="detail-pager-prev">
          <%= link_to '< 前月', wallet_summaries_show_path(:walletId => @p_walletId, year: (@p_targetDate - 1.months).year, month: (@p_targetDate - 1.months).month) %>
        </td>
        <td class="detail-pager-next">
          <%= link_to '翌月 >', wallet_summaries_show_path(:walletId => @p_walletId, year: (@p_targetDate - 1.months).year, month: (@p_targetDate + 1.months).month) %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/wallet_summaries/index.html.erb
<% @wallet_summaries.each do |summary| %>
<div class="card">
  <div class="card-header">
    <%= summary.name %>
  </div>
  <div class="card-body">
    <h1>
      <% if !summary.amount.blank? %>
      <%= summary.amount.to_s(:delimited, delimiter: ',') %>
      <% else %>
      ない
      <% end %>
    </h1>
  </div>
  <div class="card-footer">
    <%= link_to '詳細', wallet_summaries_show_path(:walletId => summary.id, :year => (@p_targetDate).year, :month => (@p_targetDate).month) %>
  </div>
</div>
<% end %>
<footer>
  <div class="card">
    <%= link_to '戻る', root_path %>
  </div>
</footer>

app/views/wallet_summaries/show.html.erb
<%= render 'detail_pager' %>
<% if @summary.length > 0 %>
<% @summary.group_by { |s| I18n.l(s.created_at, format: :date) }.map do |key, summaries| %>
<div class="card">
  <div class="card-header">
    <%= key + 'の' + @p_walletName %>
  </div>
  <table class="table">
    <thead>
      <tr class="table">
        <th>摘要</th>
        <th>金額</th>
        <th>人</th>
      </tr>
    </thead>
    <tbody>
      <% summaries.each do |summary| %>
      <tr>
        <td><%= summary.reason_name %></td>
        <td><%= summary.amount.to_s(:delimited, delimiter: ',') %></td>
        <td><%= summary.user_name %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>
<% else %>
<div class="card">
  <%= I18n.l(@p_targetDate, format: :ym) %>のデータ、なし
</div>
<% end %>
<%= render 'detail_pager' %>
<footer>
  <div class="card">
    <%= link_to '戻る', wallet_summaries_path %>
  </div>
</footer>