config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'spend_budgets/monthly/:year/:month', to: 'spend_budgets#index', as: 'spend_budgets/index'
  resources :spend_budgets

  get 'spends/:year/:month', to: 'spends#index', as: 'spends/index'
  resources :spends

  get 'incomes/:year/:month', to: 'incomes#index', as: 'incomes/index'
  resources :incomes

  resources :transfers

  resources :monthly_closings

  get 'summaries/:year/:month', to: 'summaries#index', as: 'summaries/index'
  resources :summaries

  get 'wallet_summaries', to: 'wallet_summaries#index'
  get 'wallet_summaries/:walletId/:year/:month', to: 'wallet_summaries#show', as: 'wallet_summaries/show'

  post '/callback', to: 'linebot#callback'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/income.rb
class Income < ApplicationRecord
  validates :amount, presence:true, length: {maximum: 9}, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  belongs_to :wallet
  belongs_to :income_reason, foreign_key: :income_reason_id
  belongs_to :user

  scope :search_without_transfar, ->() { where.not(income_reason_id: 999) }
end

app/models/income_reason.rb
class IncomeReason < ApplicationRecord
  has_many :income

  scope :search_without_transfar, ->() { where.not(id: 999) }
end

app/models/spend.rb
class Spend < ApplicationRecord
  validates :amount, presence:true, length: {maximum: 9}, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  belongs_to :wallet
  belongs_to :spend_reason, foreign_key: :spend_reason_id
  belongs_to :user

  scope :search_without_transfar, ->() { where.not(spend_reason_id: 999) }
  scope :search_created_at_between, -> (from, to) {
    if from.present? && to.present?
      where(created_at: from..to)
    elsif from.present?
      where('created_at >= ?', from)
    elsif to.present?
      where('created_at <= ?', to)
    end
  }
end

app/models/spend_budget.rb
class SpendBudget < ApplicationRecord
  validates :amount, presence:true, length: {maximum: 9}, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :memo, length: {maximum: 50}
  belongs_to :spend_reason, foreign_key: :spend_reason_id
  belongs_to :user

  scope :search_target_date_between, -> (from, to) {
    if from.present? && to.present?
      where(target_date: from..to)
    elsif from.present?
      where('created_at >= ?', from)
    elsif to.present?
      where('created_at <= ?', to)
    end
  }
end

app/models/spend_reason.rb
class SpendReason < ApplicationRecord
  has_many :spend
  has_many :spend_budget

  scope :search_without_transfar, ->() { where.not(id: 999) }
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/view_financial.rb
class ViewFinancial < ApplicationRecord
  belongs_to :wallet
  belongs_to :user
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  has_many :income
  has_many :spend
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  def index
    @p_targetDate = Time.zone.now
    if (params[:year].present? && params[:month].present?)
      @p_targetDate = Time.zone.local(params[:year], params[:month], 1, 0, 0, 0)
    end
    @page_type = "incomes"
    @summary = get_income_summary(@p_targetDate)
  end

  def new
    @income = Income.new()
    @del_income = find_income_by_id
  end

  def create
    @income = Income.new(income_params)
    if @income.save
      flash[:success] = "income created!" + @income.id.to_s
      redirect_to new_income_path(id: @income.id)
    else
      render 'new'
    end
  end

  def destroy
    @del_income = find_income_by_id
    @del_income.destroy
    flash[:success] = "さっきのは消しました"
    redirect_back(fallback_location: root_path)
  end

  private
  def get_income_summary(targetDate)
    summary =  Income.search_without_transfar.joins(:income_reason)
      .select(
        'incomes.id',
        'income_reasons.id AS reason_id',
        'income_reasons.name AS reason_name',
        'incomes.amount',
        'incomes.created_at AS created_at',
        'date(incomes.created_at) AS created_dt'
      )
      .where(created_at: targetDate.in_time_zone.all_month)
      .order('incomes.created_at desc')
    return summary
  end

  def income_params
    params.require(:income).permit(:amount, :wallet_id, :income_reason_id,
                                 :user_id)
  end

  def find_income_by_id
    if !params[:id].blank?
      return Income.find_by(id: params[:id])
    else
      return nil
    end
  end
end

app/controllers/spends_controller.rb
class SpendsController < ApplicationController
  def index
    @p_targetDate = Time.zone.now
    if (params[:year].present? && params[:month].present?)
      @p_targetDate = Time.zone.local(params[:year], params[:month], 1, 0, 0, 0)
    end
    @page_type = "spends"

    @summary = get_spend_summary(@p_targetDate)
  end

  def new
    @spend = Spend.new()
    @del_spend = find_spend_by_id
  end

  def create
    @spend = Spend.new(spend_params)
    if @spend.save
      flash[:success] = "spend created!" + @spend.id.to_s
      redirect_to new_spend_path(id: @spend.id)
    else
      render 'new'
    end
  end

  def destroy
    @del_spend = find_spend_by_id
    @del_spend.destroy
    flash[:success] = "さっきのは消しました"
    redirect_back(fallback_location: root_path)
  end

  private
  def get_spend_summary(targetDate)
    summary =  Spend.search_without_transfar.joins(:spend_reason)
      .select(
        'spends.id',
        'spend_reasons.id AS reason_id',
        'spend_reasons.name AS reason_name',
        'spends.amount',
        'spends.created_at AS created_at',
        'date(spends.created_at) AS created_dt'
      )
      .where(created_at: targetDate.in_time_zone.all_month)
      .order('spends.created_at desc')
    return summary
  end

  def spend_params
    params.require(:spend).permit(:amount, :wallet_id, :spend_reason_id,
                                 :user_id)
  end

  def find_spend_by_id
    if !params[:id].blank?
      f = Spend.find_by(id: params[:id])
    else
      return nil
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/linebot_helper.rb
module LinebotHelper
end

app/helpers/spend_budgets_helper.rb
module SpendBudgetsHelper
end

app/helpers/spends_helper.rb
module SpendsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/summaries_helper.rb
module SummariesHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/helpers/wallet_summary_helper.rb
module WalletSummaryHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Kakeibo</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
  <div class="wrapper">
    <header>
      <% flash.each do |message_type, message| %>
      <script>
        toastr['<%= message_type %>']('<%= message %>');
      </script>
      <% end %>
    </header>
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_detail.html.erb
<%= render 'shared/detail_pager' %>
<% if @summary.length > 0 %>
<% @summary.group_by { |s| I18n.l(s.created_at, format: :date) }.map do |key, summaries| %>
<div class="card">
  <div class="card-header">
    <% if @page_type == 'incomes' %>
    <%= key + 'の収入' %>
    <% elsif @page_type == 'spends' %>
    <%= key + 'の出費' %>
    <% end %>
  </div>
  <table class="table">
    <thead>
      <tr class="table">
        <th>摘要</th>
        <th>金額</th>
        <th>作成</th>
      </tr>
    </thead>
    <tbody>
      <% summaries.each do |summary| %>
      <tr>
        <td><%= summary.reason_name %></td>
        <td><%= summary.amount.to_s(:delimited, delimiter: ',') %></td>
        <td><%= I18n.l(summary.created_at, format: :time) %></td>
        <td><%= link_to '消す', summary, method: :delete, data: { confirm: 'マジデ？' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>
<% else %>
<div class="card">
  <%= I18n.l(@p_targetDate, format: :ym) %>のデータ、なし
</div>
<% end %>
<%= render 'shared/detail_pager' %>
<footer>
  <div class="card">
    <%= link_to '戻る', summaries_index_path(:year => (@p_targetDate).year, :month => (@p_targetDate).month) %>
  </div>
</footer>

app/views/shared/_detail_pager.html.erb
<div class="card">
  <table style="width: 100%;">
    <tbody>
      <tr>
        <% if @page_type == 'incomes' %>
        <td class="detail-pager-prev">
          <%= link_to '< 前月', incomes_index_path(:year => (@p_targetDate - 1.months).year, :month => (@p_targetDate - 1.months).month) %>
        </td>
        <td class="detail-pager-next">
          <%= link_to '翌月 >', incomes_index_path(:year => (@p_targetDate + 1.months).year, :month => (@p_targetDate + 1.months).month) %>
        </td>
        <% elsif @page_type == 'spends' %>
        <td class="detail-pager-prev">
          <%= link_to '< 前月', spends_index_path(:year => (@p_targetDate - 1.months).year, :month => (@p_targetDate - 1.months).month) %>
        </td>
        <td class="detail-pager-next">
          <%= link_to '翌月 >', spends_index_path(:year => (@p_targetDate + 1.months).year, :month => (@p_targetDate + 1.months).month) %>
        </td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    入力値が不正です。
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>