config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'spend_budgets/monthly/:year/:month', to: 'spend_budgets#index', as: 'spend_budgets/index'
  resources :spend_budgets

  get 'spends/:year/:month', to: 'spends#index', as: 'spends/index'
  resources :spends

  get 'incomes/:year/:month', to: 'incomes#index', as: 'incomes/index'
  resources :incomes

  resources :transfers

  resources :monthly_closings

  get 'summaries/:year/:month', to: 'summaries#index', as: 'summaries/index'
  resources :summaries

  get 'wallet_summaries', to: 'wallet_summaries#index'
  get 'wallet_summaries/:walletId/:year/:month', to: 'wallet_summaries#show', as: 'wallet_summaries/show'

  post '/callback', to: 'linebot#callback'
end

app/models/spend_budget.rb
class SpendBudget < ApplicationRecord
  validates :amount, presence:true, length: {maximum: 9}, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :memo, length: {maximum: 50}
  belongs_to :spend_reason, foreign_key: :spend_reason_id
  belongs_to :user

  scope :search_target_date_between, -> (from, to) {
    if from.present? && to.present?
      where(target_date: from..to)
    elsif from.present?
      where('created_at >= ?', from)
    elsif to.present?
      where('created_at <= ?', to)
    end
  }
end

app/controllers/spend_budgets_controller.rb
class SpendBudgetsController < ApplicationController
  before_action :set_spend_budget, only: [:show, :edit, :update, :destroy]

  def index
    @spend_budgets = SpendBudget.all

    @p_targetDate = Time.zone.now
    if (params[:year].present? && params[:month].present?)
      @p_targetDate = Time.zone.local(params[:year], params[:month], 1, 0, 0, 0)
    end

    @budget_summary = get_spend_budget_summary(@p_targetDate)
  end

  def new
    @spend_budget = SpendBudget.new
  end

  def edit
  end

  def create
    @spend_budget = SpendBudget.new(spend_budget_params)

    if @spend_budget.save
      flash[:success] = '予定を立てたからお金を守ろう'
      redirect_to spend_budgets_index_path(:year => (@spend_budget[:target_date]).year, :month => (@spend_budget[:target_date]).month)
    else
      render :new
    end
  end

  def update
    if @spend_budget.update(spend_budget_params)
      flash[:success] = '予定を立て直しました'
      redirect_to spend_budgets_index_path(:year => (@spend_budget[:target_date]).year, :month => (@spend_budget[:target_date]).month)
    else
      render :edit
    end
  end

  def destroy
    @spend_budget.destroy
    flash[:success] = '予定をなんてなかった、いいね？'
    redirect_to spend_budgets_url
  end

  private
    def set_spend_budget
      @spend_budget = SpendBudget.find(params[:id])
    end

    def spend_budget_params
      params.require(:spend_budget).permit(:target_date, :amount, :spend_reason_id, :user_id, :memo)
    end

    def get_spend_budget_summary(targetDate)
      return SpendBudget
        .search_target_date_between(targetDate.in_time_zone.all_month.first, targetDate.in_time_zone.all_month.last)
        .joins(:user)
        .joins(:spend_reason)
        .select(:id)
        .select('spend_reasons.name AS reason_name')
        .select('users.name AS user_name')
        .select(:amount)
        .select('spend_budgets.target_date')
        .order('spend_budgets.target_date desc')
    end
end

app/helpers/spend_budgets_helper.rb
module SpendBudgetsHelper
end

app/views/spend_budgets/_detail_pager.html.erb
<div class="card">
  <table style="width: 100%;">
    <tbody>
      <tr>
        <td class="detail-pager-prev">
          <%= link_to '< 前月', spend_budgets_index_path(:year => (@p_targetDate - 1.months).year, :month => (@p_targetDate - 1.months).month) %>
        </td>
        <td>
          <%= link_to '>当月<', spend_budgets_path %>
        </td>
        <td class="detail-pager-next">
          <%= link_to '翌月 >', spend_budgets_index_path(:year => (@p_targetDate + 1.months).year, :month => (@p_targetDate + 1.months).month) %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/spend_budgets/_form.html.erb
<%= form_with(model: spend_budget, local: true) do |f| %>

  <h2>予算を考える</h2>

  <div class="form-group">
    <%= render 'shared/error_messages', object: spend_budget %>

    <%= f.label '出費理由' %>
    <%= f.collection_select :spend_reason_id, SpendReason.all.where('id <> 999'), :id, :name , {}, { :class => 'form-control collection' } %>

    <%= f.label '登録者名' %>
    <%= f.collection_select :user_id, User.all, :id, :name , {}, { :class => 'form-control collection' } %>

    <%= f.label '対象年月' %>
    <%= f.date_select :target_date, { :discard_day => true } , { :class => 'form-control date' } %>

    <%= f.text_field :amount, :placeholder => '金額', class: 'form-control input' %>

    <%= f.text_field :memo, :placeholder => 'メモ', class: 'form-control input' %>

    <%= f.submit :class => "btn" %>
  </div>
<% end %>

app/views/spend_budgets/edit.html.erb
<%= render 'form', spend_budget: @spend_budget %>

<footer>
  <div class="card">
    <%= link_to '戻る', spend_budgets_path %>
  </div>
</footer>

app/views/spend_budgets/index.html.erb
<%= render 'detail_pager' %>

<div class="card">
  <%= link_to '新規の皮算用する', new_spend_budget_path %>
</div>

<% if @budget_summary.length > 0 %>
<% @budget_summary.group_by { |s| I18n.l(s.target_date, format: :ym) }.map do |key, summaries| %>
<div class="card">
  <div class="card-header">
    <%= key + 'の予算' %>
  </div>
  <table class="table">
    <thead>
      <tr class="table">
        <th style="width: 60px;">-</th>
        <th>摘要</th>
        <th>金額</th>
        <th>人</th>
        <th style="width: 60px;">-</th>
      </tr>
    </thead>
    <tbody>
      <% summaries.each do |summary| %>
      <tr>
        <td><%= link_to '消す', summary, method: :delete, data: { confirm: 'マジデ？' } %></td>
        <td><%= summary.reason_name %></td>
        <td><%= summary.amount.to_s(:delimited, delimiter: ',') %></td>
        <td><%= summary.user_name %></td>
        <td><%= link_to '修正', edit_spend_budget_path(summary) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>
<% else %>
<div class="card">
  <%= I18n.l(@p_targetDate, format: :ym) %>のデータ、なし
</div>
<% end %>
<%= render 'detail_pager' %>
<footer>
  <div class="card">
    <%= link_to '戻る', root_path %>
  </div>
</footer>

app/views/spend_budgets/new.html.erb
<%= render 'form', spend_budget: @spend_budget %>

<footer>
  <div class="card">
    <%= link_to '戻る', spend_budgets_path %>
  </div>
</footer>